title: Select Blah
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/selectblah" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Luke Moloney # add your name
author-img: site/luke.jpg # add your photo
about-author: I am just a person who writes about Data, Analytics and the cloud, mostly looking at Azure. I work at Microsoft as a Cloud Solution Architect for Data & AI at Microsoft. All opinions are my own and not those of Microsoft. # add description
social-twitter: lukemoloney # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lmoloney # add your Github handle
social-linkedin: moloneyluke # add your Linkedin handle
social-email: luke@lm.id.au # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
